// Generated by https://quicktype.io

export interface VariantColorsResp {
  total: number;
  variantColors: VariantColor[];
}

export interface VariantColor {
  id: number;
  name: string;
  color: string;
}

export interface VariantSizesResp {
  total: number;
  variantSizes: VariantSize[];
}

export interface VariantSize {
  id: number;
  name: string;
  short: string;
}
